/**
 * The hook launcher — the tiny `/bin/sh` shim that host configs
 * (`~/.claude/settings.json`, `~/.cursor/hooks.json`) point at instead of a
 * Node binary.
 *
 * Why it exists
 * -------------
 * The installers used to write `process.execPath` — the absolute path of
 * whatever Node happened to run the installer — into the host's config:
 *
 *     '/opt/homebrew/Cellar/node/26.0.0/bin/node' '/…/helm-hook-claude.mjs' …
 *
 * That path rots. Upgrade homebrew's node, switch nvm versions, or install
 * from the packaged Electron app (where `execPath` is the *app binary*, not
 * node at all) and every hook invocation dies with `No such file or
 * directory`. Worse, re-running the installer rewrites the same dead path,
 * so a hand-fix never survives.
 *
 * A bare `node` isn't the answer either: hosts spawn hooks from their own
 * environment, and a macOS GUI launch (Dock / Spotlight) has no user shell
 * PATH, so `node` may not resolve at all.
 *
 * So the config points at a stable path we own — `$HELM_HOME/bin/helm-hook-node`
 * — and resolution happens at *run* time, cheapest source first:
 *
 *   1. `$HELM_HOOK_NODE`             — explicit override
 *   2. `$HELM_HOME/cache/hook-node-path` — last known-good, re-validated
 *   3. `command -v node`             — terminal launch: user PATH is present
 *   4. version managers + system dirs — GUI launch: no PATH, probe disk
 *   5. `$SHELL -lc 'command -v node'` — last resort: the user's own profile
 *
 * Every candidate must exist, be executable, *and* answer `--version`, so a
 * dangling version-manager shim doesn't win. Nothing found ⇒ the launcher
 * emits the host's neutral response and exits 0: a missing Node degrades
 * helm to "not capturing", never to "the host is broken".
 *
 * The file name contains HOOK_MARKER ('helm-hook') so the installers' marker
 * matching keeps working on the generated command string.
 */

import { chmodSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { HELM_HOME, HOOK_MARKER } from '../constants.js';

/** Basename of the generated launcher. Contains HOOK_MARKER by construction. */
export const HOOK_LAUNCHER_NAME = `${HOOK_MARKER}-node`;

/**
 * HELM_HOME as of *now*, not as of module load. The constant is captured at
 * import time, which is wrong for anything that sets HELM_HOME later (tests,
 * a relocated data dir) — and this module writes a file, so it must land in
 * the same home the rest of the process is using.
 */
export function resolveHelmHome(): string {
  const fromEnv = process.env['HELM_HOME'];
  return fromEnv && fromEnv.trim() ? fromEnv.trim() : HELM_HOME;
}

/** Absolute path of the launcher for a given HELM_HOME. */
export function hookLauncherPath(helmHome: string = resolveHelmHome()): string {
  return path.join(helmHome, 'bin', HOOK_LAUNCHER_NAME);
}

/**
 * The launcher script body. Pure POSIX sh — no bashisms, no `local`, no
 * GNU-only flags — because it runs under whatever `/bin/sh` the host has.
 */
export function renderHookLauncher(): string {
  return `#!/bin/sh
# ${HOOK_LAUNCHER_NAME} — GENERATED BY HELM. Do not edit: every hook install
# rewrites this file.
#
# Resolves a working Node at run time, then execs the helm hook entry with it.
# The host config stores this path instead of an absolute node path, so
# upgrading / removing / switching node never breaks the installed hooks.
#
#   usage: ${HOOK_LAUNCHER_NAME} <hook-entry.mjs> [args…]

set -u

# A GUI-launched host can hand us an environment with an empty PATH — which
# would take /bin/mkdir, /usr/bin/date and friends with it. Guarantee the
# system dirs (plus the two usual package-manager bins) are searchable, while
# keeping whatever the user's PATH had in front.
PATH="\${PATH:+$PATH:}/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/homebrew/bin"
export PATH

HELM_HOME_DIR="\${HELM_HOME:-$HOME/.helm}"
CACHE_FILE="$HELM_HOME_DIR/cache/hook-node-path"
NVM_ROOT="\${NVM_DIR:-$HOME/.nvm}"
# Prefix for the machine-wide candidates (/opt/homebrew, /usr/local, /usr).
# Empty in production; tests point it at a sandbox so a node that happens to
# be installed on the test machine can't decide the outcome.
PROBE_ROOT="\${HELM_HOOK_PROBE_ROOT:-}"
NODE=""
MIN_MAJOR=0

# stdout belongs to the host — it parses it as the hook response — so
# diagnostics go to a file, never to stdout.
helm_log() {
  _dir="$HELM_HOME_DIR/logs"
  [ -d "$_dir" ] || mkdir -p "$_dir" 2>/dev/null || return 0
  printf '%s ${HOOK_LAUNCHER_NAME} %s\\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ' 2>/dev/null)" "$1" \\
    >>"$_dir/hook-launcher.log" 2>/dev/null || true
}

# Read the first line of a file with the shell builtin — no \`cat\`, so this
# still works if PATH is hostile.
helm_first_line() {
  _line=""
  [ -r "\${1:-}" ] || return 0
  read -r _line < "$1" 2>/dev/null || _line=""
  printf '%s' "$_line"
}

# A candidate counts only if it exists, is executable, AND actually answers
# --version with a major >= MIN_MAJOR. '-x' alone would accept a dangling nvm
# symlink or a broken asdf shim; the version floor keeps an ancient
# /usr/bin/node from shadowing the modern one the user actually uses.
helm_try() {
  [ -z "$NODE" ] || return 0
  [ -n "\${1:-}" ] || return 0
  [ -x "$1" ] || return 0
  _ver="$("$1" --version 2>/dev/null)" || return 0
  case "$_ver" in v[0-9]*) ;; *) return 0 ;; esac
  _major="\${_ver#v}"
  _major="\${_major%%.*}"
  [ "$_major" -ge "$MIN_MAJOR" ] 2>/dev/null || return 0
  NODE="$1"
}

# nvm version directory names (v22.18.0 …), newest first.
helm_nvm_versions() {
  ls -1 "$NVM_ROOT/versions/node" 2>/dev/null \\
    | sed 's/^v//' 2>/dev/null \\
    | sort -t. -k1,1nr -k2,2nr -k3,3nr 2>/dev/null \\
    | sed 's/^/v/' 2>/dev/null
}

helm_scan() {
  helm_try "\${HELM_HOOK_NODE:-}"
  helm_try "$(helm_first_line "$CACHE_FILE")"

  # Terminal launch: the host inherited the user's PATH.
  helm_try "$(command -v node 2>/dev/null)"

  # GUI launch (Dock / Spotlight): no user PATH. Probe where node lives.
  helm_try "$NVM_ROOT/current/bin/node"

  # nvm's default alias may be partial ("22.18" → v22.18.0), so match it as a
  # prefix against the real version dirs, newest first.
  _alias="$(helm_first_line "$NVM_ROOT/alias/default")"
  _alias="v\${_alias#v}"
  if [ "$_alias" != "v" ]; then
    for _v in $(helm_nvm_versions); do
      case "$_v" in
        "$_alias"|"$_alias".*) helm_try "$NVM_ROOT/versions/node/$_v/bin/node" ;;
      esac
    done
  fi

  # Any other nvm-managed version, newest first. Still a version manager the
  # user actively installed, so it outranks whatever system node happens to
  # be lying around.
  for _v in $(helm_nvm_versions); do
    helm_try "$NVM_ROOT/versions/node/$_v/bin/node"
  done

  for _c in "$HOME/.volta/bin/node" \\
            "$HOME/.local/share/mise/shims/node" \\
            "$HOME/.asdf/shims/node" \\
            "$HOME/.local/share/fnm/aliases/default/bin/node" \\
            "$HOME/Library/Application Support/fnm/aliases/default/bin/node" \\
            "$PROBE_ROOT/opt/homebrew/bin/node" \\
            "$PROBE_ROOT/usr/local/bin/node" \\
            "$PROBE_ROOT/usr/bin/node"; do
    helm_try "$_c"
  done
}

# Ask the user's login shell — it sources their profile, which is what
# rescues setups whose node lives nowhere predictable. Costs a shell startup,
# so it only runs after the cheap probes came up empty.
helm_scan_login_shell() {
  [ -z "$NODE" ] || return 0
  [ -n "\${SHELL:-}" ] && [ -x "\${SHELL:-}" ] || return 0
  helm_try "$("$SHELL" -lc 'command -v node' 2>/dev/null | tail -n 1)"
}

# helm needs a modern node (package.json engines: >=20.12). Take the best
# match first; only if the machine has nothing that new do we fall back to
# "any node at all" — a too-old node is still better than no capture, and
# whatever breaks after that at least reports itself.
MIN_MAJOR=20
helm_scan
helm_scan_login_shell
if [ -z "$NODE" ]; then
  MIN_MAJOR=1
  helm_scan
  helm_scan_login_shell
fi

if [ -z "$NODE" ]; then
  helm_log "no usable node found; hook skipped (PATH=\${PATH:-})"
  # Never break the host. Mirror the hook entries' neutral fallback: helm
  # simply doesn't observe this event.
  _event=""
  _prev=""
  for _a in "$@"; do
    case "$_a" in
      --event=*) _event="\${_a#--event=}" ;;
      *) [ "$_prev" = "--event" ] && _event="$_a" ;;
    esac
    _prev="$_a"
  done
  # Event names come from the installers, so match them exactly rather than
  # depending on \`tr\` being on PATH.
  case "$_event" in
    beforeShellExecution|beforeMCPExecution|preToolUse)
      printf '%s\\n' '{"permission":"ask","user_message":"Helm could not find a node binary to run its hook. Review this action locally."}'
      ;;
    beforeSubmitPrompt)
      printf '%s\\n' '{"continue":true}'
      ;;
    *)
      printf '%s\\n' '{}'
      ;;
  esac
  exit 0
fi

if [ "$NODE" != "$(helm_first_line "$CACHE_FILE")" ]; then
  if mkdir -p "$HELM_HOME_DIR/cache" 2>/dev/null; then
    printf '%s\\n' "$NODE" >"$CACHE_FILE" 2>/dev/null || true
  fi
  helm_log "resolved node -> $NODE"
fi

exec "$NODE" "$@"
`;
}

/**
 * Write (or rewrite) the launcher and return its path. Called on every
 * install so script improvements reach users who installed earlier.
 *
 * Throws only if the file can't be written — callers fall back to a
 * PATH-based command rather than propagating.
 */
export function ensureHookLauncher(helmHome: string = resolveHelmHome()): string {
  const target = hookLauncherPath(helmHome);
  const body = renderHookLauncher();
  let current: string | null = null;
  try { current = readFileSync(target, 'utf8'); } catch { current = null; }
  if (current !== body) {
    mkdirSync(path.dirname(target), { recursive: true });
    writeFileSync(target, body, 'utf8');
  }
  chmodSync(target, 0o755);
  return target;
}

/**
 * Shell-quote for the single-quoted style both installers use.
 */
export function shellQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

/**
 * The interpreter prefix a hook command should start with.
 *
 * POSIX: the generated launcher. If we can't write it (read-only HOME,
 * exotic sandbox), fall back to `/usr/bin/env node` — the same PATH-based
 * resolution the hook scripts' own shebangs already rely on. Windows has no
 * launcher (and the hosts quote commands differently there); plain `node`
 * is the least-wrong option and matches the shebang behaviour.
 */
export function hookInterpreterPrefix(helmHome: string = resolveHelmHome()): string {
  if (process.platform === 'win32') return 'node';
  try {
    return shellQuote(ensureHookLauncher(helmHome));
  } catch {
    return '/usr/bin/env node';
  }
}
