/**
 * Bindings — manage channel ↔ host_session relationships.
 *
 * Two sections:
 *   - Pending: codes generated by `@bot bind chat` in Lark, awaiting a chat
 *     selection on the desktop side. Click "Bind to ___" to consume.
 *   - Active: existing channel_bindings rows; "Unbind" removes one.
 *
 * Live updates via SSE — when Lark generates a new code or the user unbinds,
 * the lists refresh without polling.
 */

import { useState } from 'react';
import { ApiError, helmApi } from '../api/client.js';
import { useApi } from '../hooks/useApi.js';
import { useEventStream } from '../hooks/useEventStream.js';
import { EmptyState } from '../components/EmptyState.js';
import type { ChannelBinding, PendingBind } from '../api/types.js';

function timeUntil(iso: string): string {
  const ms = new Date(iso).getTime() - Date.now();
  if (ms <= 0) return 'expired';
  const min = Math.floor(ms / 60_000);
  if (min < 60) return `${min}m`;
  const hr = Math.floor(min / 60);
  return `${hr}h ${min % 60}m`;
}

function shortId(id: string, len = 12): string {
  return id.length > len ? `${id.slice(0, len)}…` : id;
}

function PendingRow({
  pending,
  chats,
  onBound,
}: {
  pending: PendingBind;
  chats: Array<{ id: string; cwd?: string }>;
  onBound: () => void;
}) {
  const [hostSessionId, setHostSessionId] = useState<string>(chats[0]?.id ?? '');
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function bind(): Promise<void> {
    if (!hostSessionId) { setError('Select a Cursor chat first.'); return; }
    setSubmitting(true);
    setError(null);
    try {
      await helmApi.consumePendingBind(pending.code, hostSessionId);
      onBound();
    } catch (err) {
      const msg = err instanceof ApiError ? `${err.status}: ${err.message}` : (err as Error).message;
      setError(msg);
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <article className="helm-card">
      <div className="row">
        <div style={{ flex: 1 }}>
          <div className="label">{pending.channel}</div>
          <div style={{ fontWeight: 600, fontSize: 14 }}>
            <code>{pending.code}</code>
          </div>
          {pending.externalChat && (
            <div className="label" style={{ marginTop: 6 }}>
              chat {pending.externalChat}{pending.externalThread ? ` / thread ${pending.externalThread}` : ''}
            </div>
          )}
        </div>
        <span className="helm-status warn">
          <span className="dot" />
          expires in {timeUntil(pending.expiresAt)}
        </span>
      </div>

      {chats.length === 0 ? (
        <p className="muted" style={{ marginTop: 12, marginBottom: 0 }}>
          No active Cursor chats — start one and it'll appear here.
        </p>
      ) : (
        <>
          <div style={{ display: 'flex', gap: 8, marginTop: 12, alignItems: 'center' }}>
            <select
              value={hostSessionId}
              onChange={(e) => setHostSessionId(e.target.value)}
              aria-label="Cursor chat to bind to"
              style={{ flex: 1 }}
            >
              {chats.map((c) => (
                <option key={c.id} value={c.id}>
                  {c.cwd ? `${c.cwd} (${c.id.slice(0, 8)})` : c.id}
                </option>
              ))}
            </select>
            <button
              className="primary"
              disabled={submitting}
              aria-busy={submitting}
              onClick={() => { void bind(); }}
            >
              {submitting ? 'Binding…' : 'Bind'}
            </button>
          </div>
          {error && <p className="muted" style={{ color: 'var(--danger)', marginTop: 8 }}>{error}</p>}
        </>
      )}
    </article>
  );
}

function ActiveRow({ binding, onUnbind }: { binding: ChannelBinding; onUnbind: () => void }) {
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function unbind(): Promise<void> {
    setSubmitting(true);
    setError(null);
    try {
      await helmApi.unbind(binding.id);
      onUnbind();
    } catch (err) {
      const msg = err instanceof ApiError ? err.message : (err as Error).message;
      setError(msg);
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <article className="helm-card">
      <div className="row">
        <div style={{ flex: 1 }}>
          <div className="label">{binding.channel}</div>
          <div style={{ fontSize: 14 }}>
            session{' '}
            <code title={binding.hostSessionId}>{shortId(binding.hostSessionId)}</code>
          </div>
          {(binding.externalChat || binding.externalThread) && (
            <div className="label" style={{ marginTop: 6 }}>
              {binding.externalChat ?? '?'}{binding.externalThread ? ` / ${binding.externalThread}` : ''}
            </div>
          )}
        </div>
        <button
          className="danger-outline"
          disabled={submitting}
          aria-busy={submitting}
          aria-label={`Unbind ${binding.channel} binding ${binding.id}`}
          onClick={() => { void unbind(); }}
        >
          {submitting ? 'Unbinding…' : 'Unbind'}
        </button>
      </div>
      {error && <p className="muted" style={{ color: 'var(--danger)', marginTop: 8 }}>{error}</p>}
    </article>
  );
}

export function BindingsPage() {
  const pendingQuery = useApi(() => helmApi.pendingBinds());
  const bindingsQuery = useApi(() => helmApi.bindings());
  const chatsQuery = useApi(() => helmApi.activeChats());

  useEventStream(() => {
    pendingQuery.reload();
    bindingsQuery.reload();
  }, { types: ['binding.created', 'binding.removed'] });

  return (
    <>
      <h2>Bindings</h2>
      <p className="muted">
        Connect a Cursor chat to a remote channel thread. Send <code>@bot bind chat</code> in Lark
        to generate a code, then pick the chat to mirror here.
      </p>

      <h3>Pending</h3>
      {pendingQuery.loading && <p className="muted">Loading…</p>}
      {pendingQuery.error && <p className="muted" style={{ color: 'var(--danger)' }}>{pendingQuery.error.message}</p>}
      {pendingQuery.data && pendingQuery.data.pending.length === 0 && (
        <EmptyState
          title="No pending bind codes."
          hint={<>Send <code>@bot bind chat</code> in a Lark thread to generate one.</>}
        />
      )}
      {pendingQuery.data?.pending.map((p) => (
        <PendingRow
          key={p.code}
          pending={p}
          chats={(chatsQuery.data?.chats ?? []).map((c) => ({ id: c.id, cwd: c.cwd }))}
          onBound={() => {
            pendingQuery.reload();
            bindingsQuery.reload();
          }}
        />
      ))}

      <h3>Active</h3>
      {bindingsQuery.loading && <p className="muted">Loading…</p>}
      {bindingsQuery.error && <p className="muted" style={{ color: 'var(--danger)' }}>{bindingsQuery.error.message}</p>}
      {bindingsQuery.data && bindingsQuery.data.bindings.length === 0 && (
        <EmptyState
          title="No active bindings."
          hint="Once you bind a Cursor chat to a remote thread, it'll appear here."
        />
      )}
      {bindingsQuery.data?.bindings.map((b) => (
        <ActiveRow
          key={b.id}
          binding={b}
          onUnbind={() => bindingsQuery.reload()}
        />
      ))}
    </>
  );
}
