/**
 * Bindings — manage channel ↔ host_session relationships.
 *
 * Two sections:
 *   - Pending: codes generated by `@bot bind chat` in Lark, awaiting a chat
 *     selection on the desktop side. Click "Bind to ___" to consume.
 *   - Active: existing channel_bindings rows; "Unbind" removes one.
 *
 * Live updates via SSE — when Lark generates a new code or the user unbinds,
 * the lists refresh without polling.
 */

import { useEffect, useState } from 'react';
import { toast } from 'sonner';
import { ApiError, helmApi } from '../api/client.js';
import { useApi } from '../hooks/useApi.js';
import { useEventStream } from '../hooks/useEventStream.js';
import { EmptyState } from '../components/EmptyState.js';
import { Button } from '../components/Button.js';
import { Card } from '../components/Card.js';
import { ConfirmDialog } from '../components/Dialog.js';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '../components/Select.js';
import { CardSkeletonList } from '../components/Skeleton.js';
import { PageHeader } from '../components/PageHeader.js';
import { StatTile } from '../components/StatTile.js';
import type { ActiveChat, ChannelBinding, PendingBind } from '../api/types.js';

function timeUntil(iso: string): string {
  const ms = new Date(iso).getTime() - Date.now();
  if (ms <= 0) return 'expired';
  const min = Math.floor(ms / 60_000);
  if (min < 60) return `${min}m`;
  const hr = Math.floor(min / 60);
  return `${hr}h ${min % 60}m`;
}

function shortId(id: string, len = 12): string {
  return id.length > len ? `${id.slice(0, len)}…` : id;
}

function truncate(s: string, max = 60): string {
  if (s.length <= max) return s;
  return `${s.slice(0, max - 1).trimEnd()}…`;
}

/**
 * Most human-readable label for a Cursor chat. Priority chain:
 *   Phase 55: displayName (user-set chat rename — highest priority)
 *   Phase 36/32: firstPrompt
 *   cwd
 *   short id (last resort)
 *
 * Active Chats page has the same chain in its own renderer; the duplicate
 * here is a known fork — keep them in sync when adding new label sources.
 */
function chatLabel(chat: ActiveChat | undefined, fallbackId: string): string {
  if (chat?.displayName) return truncate(chat.displayName);
  if (chat?.firstPrompt) return truncate(chat.firstPrompt);
  if (chat?.cwd) return chat.cwd;
  return shortId(fallbackId);
}

function PendingRow({
  pending,
  chats,
  onBound,
  onCancelled,
}: {
  pending: PendingBind;
  chats: ActiveChat[];
  onBound: () => void;
  onCancelled: () => void;
}) {
  const [hostSessionId, setHostSessionId] = useState<string>(chats[0]?.id ?? '');
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  // helm-design PR 3: replace window.confirm with themed ConfirmDialog.
  const [confirmCancel, setConfirmCancel] = useState(false);

  // Phase 40: chats load asynchronously — when this row mounts before
  // chatsQuery resolves, useState locks `hostSessionId` to ''. The native
  // <select> then visually shows the first option (because no value matches
  // empty), but state stays '', so Bind reports "Select a Cursor chat first"
  // even though the user sees a valid choice. Sync once chats arrive.
  useEffect(() => {
    if (!hostSessionId && chats.length > 0) {
      setHostSessionId(chats[0]!.id);
    }
  }, [chats, hostSessionId]);

  async function bind(): Promise<void> {
    if (!hostSessionId) { setError('Select a Cursor chat first.'); return; }
    setSubmitting(true);
    setError(null);
    try {
      await helmApi.consumePendingBind(pending.code, hostSessionId);
      onBound();
    } catch (err) {
      const msg = err instanceof ApiError ? `${err.status}: ${err.message}` : (err as Error).message;
      setError(msg);
    } finally {
      setSubmitting(false);
    }
  }

  // Phase 39: dismiss a pending code without consuming it. Useful for
  // clearing accidental codes / stale entries instead of waiting for the
  // 10-minute TTL. Confirms before deleting since the code is then gone.
  async function cancel(): Promise<void> {
    setSubmitting(true);
    setError(null);
    try {
      await helmApi.cancelPendingBind(pending.code);
      onCancelled();
    } catch (err) {
      const msg = err instanceof ApiError ? `${err.status}: ${err.message}` : (err as Error).message;
      setError(msg);
    } finally {
      setSubmitting(false);
      setConfirmCancel(false);
    }
  }

  return (
    <Card>
      <div className="row">
        <div style={{ flex: 1 }}>
          <div className="label">{pending.channel}</div>
          <div style={{ fontWeight: 600, fontSize: 14 }}>
            <code>{pending.code}</code>
          </div>
          {pending.externalChat && (
            <div className="label" style={{ marginTop: 6 }}>
              chat {pending.externalChat}{pending.externalThread ? ` / thread ${pending.externalThread}` : ''}
            </div>
          )}
        </div>
        <span className="helm-status warn">
          <span className="dot" />
          expires in {timeUntil(pending.expiresAt)}
        </span>
      </div>

      {chats.length === 0 ? (
        <>
          <p className="muted" style={{ marginTop: 12, marginBottom: 0 }}>
            No active Cursor chats — start one and it'll appear here.
          </p>
          <div style={{ display: 'flex', gap: 8, marginTop: 12 }}>
            <Button
              type="button"
              variant="danger-outline"
              disabled={submitting}
              onClick={() => setConfirmCancel(true)}
              aria-label={`Cancel pending bind code ${pending.code}`}
            >
              {submitting ? 'Cancelling…' : 'Cancel'}
            </Button>
          </div>
        </>
      ) : (
        <>
          <div style={{ display: 'flex', gap: 8, marginTop: 12, alignItems: 'center' }}>
            <Select
              value={hostSessionId}
              onValueChange={setHostSessionId}
            >
              <SelectTrigger aria-label="Cursor chat to bind to" style={{ flex: 1 }}>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {chats.map((c) => (
                  <SelectItem key={c.id} value={c.id}>
                    {chatLabel(c, c.id)}{c.cwd && c.firstPrompt ? ` — ${c.cwd}` : ''} ({c.id.slice(0, 8)})
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            <Button
              variant="primary"
              disabled={submitting}
              aria-busy={submitting}
              onClick={() => { void bind(); }}
            >
              {submitting ? 'Binding…' : 'Bind'}
            </Button>
            {/* Phase 39: cancel a pending code without binding it.
                Lives next to Bind so the user can dismiss accidental /
                stale codes inline. */}
            <Button
              type="button"
              variant="danger-outline"
              disabled={submitting}
              onClick={() => setConfirmCancel(true)}
              aria-label={`Cancel pending bind code ${pending.code}`}
            >
              Cancel
            </Button>
          </div>
          {error && <p className="muted" style={{ color: 'var(--danger)', marginTop: 8 }}>{error}</p>}
        </>
      )}

      <ConfirmDialog
        open={confirmCancel}
        onOpenChange={setConfirmCancel}
        title={`Cancel pending bind code ${pending.code}?`}
        description={'This discards the code without binding. The user will need to send "@bot bind chat" again to get a new one.'}
        confirmLabel="Cancel code"
        cancelLabel="Keep"
        onConfirm={() => { void cancel(); }}
        busy={submitting}
      />
    </Card>
  );
}

function ActiveRow({
  binding,
  chat,
  onUnbind,
}: {
  binding: ChannelBinding;
  chat?: ActiveChat;
  onUnbind: () => void;
}) {
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function unbind(): Promise<void> {
    setSubmitting(true);
    setError(null);
    try {
      await helmApi.unbind(binding.id);
      onUnbind();
    } catch (err) {
      const msg = err instanceof ApiError ? err.message : (err as Error).message;
      setError(msg);
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <Card>
      <div className="row">
        <div style={{ flex: 1 }}>
          {/* Phase 36: top line carries the user's annotation label (from
              `bind chat <hint>`) when present, then channel name. */}
          <div className="label">
            {binding.channel}{binding.label ? <> · &ldquo;{binding.label}&rdquo;</> : null}
          </div>
          {/* Phase 36: human-readable Cursor chat label (firstPrompt → cwd → id).
              When the host_session row was deleted, fall back to the binding's
              stored hostSessionId so this never reads as blank. */}
          <div style={{ fontWeight: 600, fontSize: 14 }} title={chat?.displayName ?? chat?.firstPrompt ?? chat?.cwd ?? binding.hostSessionId}>
            {chatLabel(chat, binding.hostSessionId)}
          </div>
          <div className="label" style={{ marginTop: 6 }}>
            {chat?.cwd && chat?.firstPrompt ? <>{chat.cwd} • </> : null}
            session <code title={binding.hostSessionId}>{shortId(binding.hostSessionId)}</code>
          </div>
          {(binding.externalChat || binding.externalThread) && (
            <div className="label" style={{ marginTop: 6 }}>
              {binding.channel}: {binding.externalChat ?? '?'}{binding.externalThread ? ` / ${binding.externalThread}` : ''}
            </div>
          )}
        </div>
        <Button
          variant="danger-outline"
          disabled={submitting}
          aria-busy={submitting}
          aria-label={`Unbind ${binding.channel} binding ${binding.id}`}
          onClick={() => { void unbind(); }}
        >
          {submitting ? 'Unbinding…' : 'Unbind'}
        </Button>
      </div>
      {error && <p className="muted" style={{ color: 'var(--danger)', marginTop: 8 }}>{error}</p>}
    </Card>
  );
}

export function BindingsPage() {
  const pendingQuery = useApi(() => helmApi.pendingBinds());
  const bindingsQuery = useApi(() => helmApi.bindings());
  const chatsQuery = useApi(() => helmApi.activeChats());

  useEventStream(() => {
    pendingQuery.reload();
    bindingsQuery.reload();
  }, { types: ['binding.created', 'binding.removed'] });

  // helm-design PR 9: load errors → toasts. Dedupe id per query so a
  // sustained outage doesn't stack a tower of toasts.
  useEffect(() => {
    if (pendingQuery.error) {
      toast.error(`Pending binds: ${pendingQuery.error.message}`, { id: 'bindings-pending' });
    }
  }, [pendingQuery.error]);
  useEffect(() => {
    if (bindingsQuery.error) {
      toast.error(`Active bindings: ${bindingsQuery.error.message}`, { id: 'bindings-active' });
    }
  }, [bindingsQuery.error]);

  // helm-design PR 6: stats summarize the page's two lists.
  const pendingCount = pendingQuery.data?.pending.length ?? 0;
  const activeCount = bindingsQuery.data?.bindings.length ?? 0;

  return (
    <>
      <PageHeader
        title="Bindings"
        subtitle={<>Connect a Cursor chat to a remote channel thread. Send <code>@bot bind chat</code> in Lark to generate a code, then pick the chat to mirror here.</>}
        stats={<>
          <StatTile label="Pending" value={pendingCount} tone={pendingCount > 0 ? 'warn' : 'muted'} />
          <StatTile label="Active" value={activeCount} tone={activeCount > 0 ? 'info' : 'muted'} />
        </>}
      />

      <h3>Pending</h3>
      {pendingQuery.loading && <CardSkeletonList n={2} />}
      {pendingQuery.data && pendingQuery.data.pending.length === 0 && (
        <EmptyState
          title="No pending bind codes."
          hint={<>Send <code>@bot bind chat</code> in a Lark thread to generate one.</>}
        />
      )}
      {pendingQuery.data?.pending.map((p) => (
        <PendingRow
          key={p.code}
          pending={p}
          chats={chatsQuery.data?.chats ?? []}
          onBound={() => {
            pendingQuery.reload();
            bindingsQuery.reload();
          }}
          onCancelled={() => pendingQuery.reload()}
        />
      ))}

      <h3>Active</h3>
      {bindingsQuery.loading && <CardSkeletonList n={2} />}
      {bindingsQuery.data && bindingsQuery.data.bindings.length === 0 && (
        <EmptyState
          title="No active bindings."
          hint="Once you bind a Cursor chat to a remote thread, it'll appear here."
        />
      )}
      {bindingsQuery.data?.bindings.map((b) => (
        <ActiveRow
          key={b.id}
          binding={b}
          chat={chatsQuery.data?.chats.find((c) => c.id === b.hostSessionId)}
          onUnbind={() => bindingsQuery.reload()}
        />
      ))}
    </>
  );
}
